# Generated by Django 2.0.7 on 2018-08-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email:')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Имя:')),
                ('last_name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Фамилия:')),
                ('city', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Город:')),
                ('is_director', models.BooleanField(default=False, verbose_name='Директор:')),
                ('is_chief', models.BooleanField(default=False, verbose_name='Начальник отдела:')),
                ('is_substitute_chief', models.BooleanField(default=False, verbose_name='Зам,Начальник отдела:')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('staff', models.BooleanField(default=False, verbose_name='Сотрудник')),
                ('admin', models.BooleanField(default=False, verbose_name='Администратор')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Аккаунт',
                'verbose_name_plural': 'Аккаунты',
            },
        ),
    ]
