# Generated by Django 2.0.7 on 2018-08-23 14:06

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название:')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=8000, null=True, verbose_name='Описание:')),
            ],
            options={
                'verbose_name': 'Цель(Главная задача)',
                'verbose_name_plural': 'Цели(Главные задачи)',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название:')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, max_length=8000, null=True, verbose_name='Описание:')),
                ('deadline', models.DateField(verbose_name='Срок До:')),
                ('closetime', models.DateField(verbose_name='Завершена в:')),
                ('department', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_department', to='departments.Department')),
                ('executor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_executor', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('main_task', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_task', to='tasks.MainTask', verbose_name='Цель')),
                ('subdivision', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_sub', to='departments.Subdivision', verbose_name='Мое подрахделение:')),
                ('watchers', models.ManyToManyField(blank=True, default=None, related_name='task_watchers', to=settings.AUTH_USER_MODEL, verbose_name='Наблюдатели')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='TaskTimestamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(default=0, verbose_name='Потрачено времени в сек.')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_timestamp', to='tasks.Task', verbose_name='задача')),
            ],
            options={
                'verbose_name': 'Время на задачу',
                'verbose_name_plural': 'Задачи и время потраченное на них',
            },
        ),
    ]
