# Generated by Django 2.0.7 on 2018-08-25 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20180825_0545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Название:')),
                ('description', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Описание:')),
                ('filepath', models.FileField(default=None, max_length=500, upload_to='media/documents/', verbose_name='Файл:')),
                ('order', models.BooleanField(default=False, verbose_name='Приказ')),
            ],
            options={
                'verbose_name': 'Документы',
            },
        ),
        migrations.AddField(
            model_name='maintask',
            name='document',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_task_document', to='tasks.Document', verbose_name='Приклипленные документ:'),
        ),
        migrations.AddField(
            model_name='task',
            name='document',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_document', to='tasks.Document', verbose_name='Приклипленные документ:'),
        ),
    ]
