# Generated by Django 2.0.7 on 2018-08-23 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Название:')),
                ('description', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Описание:')),
                ('chief', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL, verbose_name='Начальник отдела:')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Название:')),
                ('city', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Город:')),
                ('description', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Описание:')),
            ],
            options={
                'verbose_name': 'Подраздиление',
                'verbose_name_plural': 'Подразделения',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='subdivision',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='departments.Subdivision', verbose_name='Мое подрахделение:'),
        ),
        migrations.AddField(
            model_name='department',
            name='substitute_chief',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Зам. Начальника отдела:'),
        ),
    ]
